### ISSUE TITLE
Publish

### ISSUE THREAD

**Issue by CrackerakiUA** [maxleiko/npmi#10]
how can we publish with your module, if can we?

**Comment by maxleiko** [comment]
You cannot. It's not meant to publish things, it's meant to install them.

**Comment by maxleiko** [comment]
However, here is how you can publish things programatically:
https://github.com/maxleiko/grunt-publish/blob/master/tasks/lib/npm-publisher.js

**Comment by CrackerakiUA** [comment]
Great, thank you.
