### ISSUE TITLE
return a promise if called with just 1 argument

### ISSUE THREAD

**Issue by capaj** [maxleiko/npmi#12]
would be nice if this also returned a promise

**Comment by RobinMalfait** [comment]
You can do it like this:

```js
return new Promise((resolve, reject) => {
  npmi(options, (err, result) => {
    return err
      ? reject(err)
      : resolve(result)
  });
});
```

**Comment by maxleiko** [comment]
Yeah, or with any Promises library if you are not sure that the `Promise` global will be available.  
Something like `es6-promise` polyfill will do the trick.  

Gonna close that as I don't want to add another dependency to `npmi`. I'd rather like you to add it as a dependency to your project if you really want it.
