### ISSUE TITLE
Is the result deterministic?

### ISSUE THREAD

**Issue by davej** [maxleiko/npmi#17]
Specifically I am looking for the top-level package name and version that was installed (not one of it's dependencies). This seems to be the last element of the result array is this always true?

I am using something like:

```js
npmi({name: 'my-pkg'}, function (err, result) {
  if (!err) console.log(res[res.length - 1][0]) // -> my-pkg@1.0.0
});
```

Is the array lookup a reliable way to get the top-level install?

**Comment by maxleiko** [comment]
Hello @davej that is definitely not a good way to test it. If npm decides to change the format of the output your code will be irrelevant.
I'd rather advise to verify that the installed package is where it should be in your filesystem and even better do a checksum verification. But that would also mean that you don't trust npm in itself :)

**Comment by maxleiko** [comment]
After all, if npmi's callback has an undefined "err" then you just have to read your installed module's `package.json` and you will get the specific installed version.

**Comment by davej** [comment]
The problem is that it's very difficult to know where the module will be stored. The`name` used by npmi is not necessarily the folder where it is installed. Particularly when installing git repos. Any tips?

**Comment by maxleiko** [comment]
Oh, mea culpa. The `results` content is totally trustable.  
*NB: never reply to issues past midnight.*

Your code is totally fine, I thought you were parsing the log output of npm. But the `results` given to the `npmi` callback is totally different. **Yes**, you can trust it. 100%.

**Comment by davej** [comment]
Thanks! The order is deterministic too right? i.e.. The last item in the array will be the root installed dep?

**Comment by maxleiko** [comment]
Yup :+1:
