### ISSUE TITLE
Pass in npm as an option

### ISSUE THREAD

**Issue by jonaskello** [maxleiko/npmi#20]
I use webpack to bundle my server. Webpack wants to exchange every `require` with it's own `__webpack_require__` which does not play well with global-npm becuase it does require on npm and it should of course not be bundled. 

It is possible to use `__non_webpack_require__` to make a regular require as explained [here](https://github.com/webpack/webpack/issues/4175#issuecomment-277232067). However I cannot use that since npmi internally calls on global-npm which in turn has the `require` I want to change to `__non_webpack_require__`.

To resolve this, it would be nice if npmi could accept an override of npm in it's options.

Something like this:

```
npm      = options.npm || require('global-npm'),
```

Then I could require npm any way I want in my app, and just pass it in.

If the above makes sense I could provide a PR for it.

**Comment by maxleiko** [comment]
Hello @jonaskello,

Thanks for using `npmi` :)

Correct me if I'm wrong, but can't you just override webpack's "require" by settings a property in your `package.json` as in:

```json
{
  "name": "your-awesome-module",
  "version": "1.2.3",
  "browser": {
    "npmi": "./browser/my-own-npmi.js"
  },
}
```

Because, anyway, npmi is just a wrapper around `npm`, and `npm` won't work in your browser.  
Webpack will never achieve the bundling. So you'll have to shim the behavior of `npmi` with something that resolve modules from [unpkg](https://unpkg.com/#/) for instance.

**Comment by maxleiko** [comment]
Something like this: https://github.com/maxleiko/npmi-issue-20

**Comment by maxleiko** [comment]
So yeah, for the explanation:

This a dummy module that needs `npmi` to download something when it is started (it downloads `lodash` as you can see in `app.js`).  
So, this works perfectly on Node.js, but if you try to bundle it for the browser using **webpack**, then you can see in the `package.json` that there is a `browser` field that specifies a shim for `npmi`.  
Webpack knows that everywhere in your application, if you have a `require('npmi')`, you will get a require to your shim instead. It allows you to specify a different Javascript to be executed only for browser environment.

Hope it answers your question.

**Comment by jonaskello** [comment]
Wow, thanks for the detailed example and explanation :-).

I am bundling my server with webpack. So basically I bundle to a server.js and then run it with node. So the browser is not involved. I know this is a somewhat unusual use of webpack so I should probably have stated that more clearly. Inside the bundled server.js I try to install a npm package with npmi. It works all the way until global-npm does require on npm. The error I got was something like `Cannot find module 'npm'` at the line where global-npm does require on npm, and the stacktrace was `__webpack_require__`. This is why I think it is due to webpack replacing all the requires with it's own implementation unless you use `__non_webpack_require__` instead.

I did a test by including both npmi.js and global-npm.js in my own code and switching out the require of npm in global-npm for `__non_webpack_require__` and then it worked. While doing this I realised that my proposed solution would break the [this line](https://github.com/maxleiko/npmi/blob/master/npmi.js#L196) (`npmi.NPM_VERSION = npm.version;`) as it assumes that npm is loaded before you call into the npmi() function, so I had to remove that in my version.

In the end I realised that I wanted to install the package without installing dependencies and I'm not sure that is what npmi is designed to do, so I might have to do it some other way.

**Comment by maxleiko** [comment]
`npmi` is just a wrapper around `npm`, so it can only do what `npm` can do.  
Installing a package without its dependencies will, almost inevitably, make it throw 'Module not found' right after start.

On the other hand, I'm interested in knowing why you want to bundle your server-side files though?
