### ISSUE TITLE
Expose version of npm used.

### ISSUE THREAD

**Issue by bestander** [maxleiko/npmi#3]
I am using this lib for my shrinkwrapping-like CLI tool https://github.com/bestander/npm-git-lock.

Considering the changes that may be coming in npm@3.0 it may be important to keep a record with what version of npm was used when install was made.

Can npmi expose the version of npm being used?
Then I would just add it as commit comment.

**Comment by maxleiko** [comment]
`npmi@1.0.1` released

You can access `npm` version with:

```js
var npmi = require('npmi');
console.log(npmi.NPM_VERSION);
```
