### ISSUE TITLE
Bump to npm3

### ISSUE THREAD

**Issue by avindra** [maxleiko/npmi#5]
Hi,

npm3 is out and ships with node5. Can you add support for it? Currently this is being used by ncu, and npm2 is being installed which seems redundant.

**Comment by maxleiko** [comment]
I'll have a look at the API changes if there are any. Keep in touch

**Comment by maxleiko** [comment]
https://github.com/npm/npm/issues/10380

Interesting reading though :)

**Comment by maxleiko** [comment]
@avindra check-out v2.0.0-alpha and tell me if anything breaks.

**Comment by metaraine** [comment]
alpha versions should not be published to the `latest` tag.

You can publish prerelease versions like this:
`npm publish --tag next`

Then users can install the prerelease version like so:
`npm install npmi@next`

**Comment by maxleiko** [comment]
True. Unpublished 2.0.0-alpha and published 2.0.1-alpha on tag `next`  
`latest` is still 1.0.1

**Comment by maxleiko** [comment]
Any feedbacks ? @avindra @metaraine

**Comment by rixrix** [comment]
hi @maxleiko your comment from 3/Dec doesn't seem to work or probably just my machine but I'm still getting npm `"version": "2.14.15"` when I tried this command `npm i npmi@next`, looking at the installed npmi module it's on version 1.0.1 and the npm deps is `"npm": "^2.1.12"`. Hope that helps. tnx

my env:
- node v4.2.4
- npm v3.5.3
- Mac on El Capitan

**Comment by maxleiko** [comment]
@rixrix that's weird, it works perfectly here. Running `npm i npmi@next` installs `2.0.1-alpha` which depends on `npm@^3`

**Comment by rixrix** [comment]
@maxleiko I guess it's my machine, I had to do `npm clear cache` before reinstalling the package and got `npm@^3` cheers

**Comment by maxleiko** [comment]
Alright.  
I think I can close that.
