### ISSUE TITLE
Save to package.json dependencies on install?

### ISSUE THREAD

**Issue by jmwohl** [maxleiko/npmi#6]
I don't see a way to do it via this module, but just in case... any way to add the equivalent of the '--save' flag when installing a package?

The `checkInstalled` function reads the package.json to see if the package@version is already installed. In my use case, npmi might get called more than once, but since it doesn't add the installed package to package.json, the packages get reinstalled each time as opposed to being skipped if they are in fact already installed.

**Comment by maxleiko** [comment]
@jmwohl do you target npm@^2 or npm@^3 ?

**Comment by jmwohl** [comment]
Recently switched to npm@^3.

For what it's worth, I've decided just to create a very basic utility that calls npm via exec... a bit more flexible, no need to learn a new syntax for npm, and it uses the locally installed instance of npm rather than pulling down the hefty npm package itself as a dependency.

**Comment by metaraine** [comment]
@jmwohl I would be interested in that. npm-check-updates seems to still be [having some issues](https://github.com/tjunnone/npm-check-updates/issues/173#issuecomment-171928257) with conflicting versions of npm which trace back to npmi.

**Comment by jmwohl** [comment]
@metaraine Cool. At the moment it's intermingled with another project, but I'll see about packaging it up into a standalone module. 

You could check out [enpeem](https://github.com/balderdashy/enpeem), it works along similar lines. Minimal functionality, but works along the lines I mentioned.

**Comment by metaraine** [comment]
Sweet, thanks.

**Comment by maxleiko** [comment]
@jmwohl @metaraine Already done that ;) https://github.com/maxleiko/exec-npm-install

**Comment by jmwohl** [comment]
@maxleiko Ah, cool!

**Comment by maxleiko** [comment]
Can I close this issue then ? @jmwohl

**Comment by jmwohl** [comment]
@maxleiko Yep, thanks.
