### ISSUE TITLE
--save option ? 

### ISSUE THREAD

**Issue by jaumard** [maxleiko/npmi#8]
Is this possible to use npmi and have --save option to save it on the package.json ?

**Comment by maxleiko** [comment]
Currently it is not possible, but it is not really hard to provide a way to do it. Which version of `npmi` are you using?

**Comment by jaumard** [comment]
Currently none :D in fact I need for my plugin system a way to Install/Uninstall plugin from code and the possibility to --save would be nice for backup ect...

**Comment by dabbott** [comment]
Passing the `npmLoad` option works for me :)

```
npmLoad: {
  save: true,
  loglevel: 'silent',
}
```

Just a direct passthrough to set npm's config `save` to true. Not sure if this has any negative consequences - haven't run into any yet though.

**Comment by maxleiko** [comment]
Nope you are totally right @dabbott that will do the trick perfectly.
