### ISSUE TITLE
Maybe use npm as a peerDependency instead of a hard dependency

### ISSUE THREAD

**Issue by maxleiko** [maxleiko/npmi#9]

**Comment by karanjthakkar** [comment]
@maxleiko Would you be willing to accept a PR that uses https://www.npmjs.com/package/global-npm to get global npm module and use that instead of a locally installed npm? This would also make it easy for us to solve https://github.com/tjunnone/npm-check-updates/pull/369

**Comment by maxleiko** [comment]
@karanjthakkar yes sure.

**Comment by karanjthakkar** [comment]
Done 💯

**Comment by maxleiko** [comment]
`npmi@4.0.0` released  
Thanks @karanjthakkar
